### ISSUE TITLE
管理员权限运行报错2021/8/5 16:44:33] 对路径“C:\WINDOWS\system32\drivers\etc\hosts”的访问被拒绝。

### ISSUE THREAD

**Issue by A403** [NS-Sp4ce/HLV_Keygen#1]
![image](https://user-images.githubusercontent.com/59276674/128320563-981ab2bd-d671-4abc-aa97-903078a0487b.png)
2021/8/5 16:44:33] 对路径“C:\WINDOWS\system32\drivers\etc\hosts”的访问被拒绝。

**Comment by NS-Sp4ce** [comment]
右键管理员运行，需要修改hosts

**Comment by A403** [comment]
已经使用管理员权限
![1.gif](https://i.loli.net/2021/08/05/WkIAXuE5dyi8TYq.gif)

**Comment by NS-Sp4ce** [comment]
是否有安全软件拦截？ 我本地测试无此问题

**Comment by A403** [comment]
本地就一个火绒。应该不拦截修改hosts，已经退出，依旧不行

**Comment by NS-Sp4ce** [comment]
手动修改hosts试试

**Comment by A403** [comment]
解决了，应该是navicat破解的时候把hosts变成只读了
